# Generated by Django 3.0.3 on 2020-07-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_auto_20200701_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
