# Generated by Django 3.0.3 on 2020-07-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_auto_20200702_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='branch_name',
            new_name='bank_name',
        ),
    ]
